### ISSUE TITLE
[Bug] Minor Formatting Issue With Widgets Disabled

### ISSUE THREAD

**Issue by LeeThompson** [erohtar/Dasherr#11] opened 2022-12-04 05:53 UTC
There is a minor formatting issue with widgets disabled.

See image for details.
![temp](https://user-images.githubusercontent.com/1982261/205476794-e846751c-cf6d-48de-b4e1-ad998ff28130.jpg)

**Comment by erohtar** [comment] 2022-12-04 07:46
There's a sample settings file included in the release that has no widgets, and it doesn't look like that for me.
Could you pls share your settings file with me so I can replicate?

**Comment by LeeThompson** [comment] 2022-12-04 20:51
Here you go.
I redacted the intranet URLs but it should be enough to show the issue.  

[settings.zip](https://github.com/erohtar/Dasherr/files/10149431/settings.zip)

**Comment by erohtar** [comment] 2022-12-05 13:35
Thank you! 
Actually I was wrong, either the CSS was cached on my end or the issue itself was caused by one of my last changes that I didn't fully test on all pages, but after testing your settings I tried and could replicate on mine too.
Should be fixed in the latest release - please try it out.

**Closed as completed by erohtar** 2022-12-05 13:36 UTC
